server:  
  port: 8212
  
spring:
  application:    
    name: gatewayservice

zuul:
  routes:    
    eureka:
      path: /eureka/**
      url: http://localhost:8761/
    data:
      path: /associates
      service-id: dataservice
    reports:
      path: /hello
      service-id: reportsservice